---
name: doppler-secrets
description: Sets secrets from Doppler as environment variables
author: https://github.com/muhlba91
requirements:
  - doppler
configuration:
  properties:
    token:
      type: string
    project:
      type: string
    project-config:
      type: string
    secrets:
      type: array
  required: []
  additionalProperties: false
