---
name: Conform

on:
  push:
  workflow_dispatch:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conform
        uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
